// Generate background image at random
function imgset() {
    //declare an array
    var randomImage = new Array();

    //insert the URL of images in array  
    randomImage[0] = "res/bg/en-pop-gallery1.jpg";
    randomImage[1] = "res/bg/en-pop-gallery2.jpg";
    randomImage[2] = "res/bg/en-pop-gallery3.jpg";
    randomImage[3] = "res/bg/en-pop-gallery4.jpg";
    randomImage[4] = "res/bg/en-pop-gallery5.jpg";
	randomImage[5] = "res/bg/en-pop-gallery6.jpg";
	randomImage[6] = "res/bg/en-pop-gallery7.jpg";
	randomImage[7] = "res/bg/en-pop-gallery8.jpg";
	randomImage[8] = "res/bg/en-pop-gallery9.jpg";
	randomImage[9] = "res/bg/en-pop-gallery10.jpg";
	randomImage[10] = "res/bg/en-pop-gallery11.jpg";
	randomImage[11] = "res/bg/en-pop-gallery12.jpg";
	randomImage[12] = "res/bg/en-pop-gallery13.jpg";
	randomImage[13] = "res/bg/en-pop-gallery14.jpg";

    //generate a number 
    var number = Math.floor(Math.random() * randomImage.length);

    //return the images generated by number 
    return randomImage[number];
}